version: '3'

services:
  server:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8080}:${APP_PORT:-8080}'
    volumes:
      - './usercontent:/opt/code/usercontent'
      # uncomment this for debug mode
      #- './:/opt/code'
    restart: always